dataset: yellow
base_url: https://d37ci6vzurychx.cloudfront.net/trip-data
taxi_zone_lookup_url: https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv

required_columns:
  - tpep_pickup_datetime
  - tpep_dropoff_datetime
  - trip_distance
  - PULocationID
  - DOLocationID
  - fare_amount
  - total_amount

optional_columns:
  - VendorID
  - passenger_count
  - RatecodeID
  - store_and_fwd_flag
  - payment_type
  - tip_amount
  - tolls_amount
  - improvement_surcharge
  - congestion_surcharge
  - Airport_fee
  - cbd_congestion_fee

quality:
  max_trip_hours: 12
  max_trip_distance_miles: 300
  max_total_amount: 5000
  valid_location_min: 1
  valid_location_max: 265
